version: '3.0'
services:
  wechat:
    build: ./wechat
    ports:
     - 80:80
  rasa:
    image: rasa/rasa:1.4.5-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  action_server:
    image: rasa/rasa-sdk:1.5.0
    volumes:
      - ./actions:/app/actions